### ISSUE TITLE
Update to latest version of fluid framework?

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/brainstorm-fluidframework-m365-azure#16]
It looks like shortly after this was published, Fluid Framework released v1.0 with a long laundry list of breaking changes. Since this seems to be one of the only examples of how to use the `AzureClient` (most of the existing examples just use Tinylicious client), and someone forgot to update [the docs](https://docs.microsoft.com/en-us/azure/azure-fluid-relay/how-tos/connect-fluid-azure-service) before pushing v1.0, any chance this project might be updated so consumers have at least one working example?

**Comment by panjkov** [comment]
Hi Andrew,

Up-to-date version of the sample is here
https://github.com/microsoft/FluidExamples/tree/main/brainstorm

Hope this helps,
Dragan

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Andrew Craswell ***@***.***>
Sent: Monday, 20 June 2022, 07:08
To: microsoft/brainstorm-fluidframework-m365-azure ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/brainstorm-fluidframework-m365-azure] Update to latest version of fluid framework? (Issue #16)


It looks like shortly after this was published, Fluid Framework released v1.0 with a long laundry list of breaking changes. Since this seems to be one of the only examples of how to use the AzureClient (most of the existing examples just use Tinylicious client), and someone forgot to update the docs<https://docs.microsoft.com/en-us/azure/azure-fluid-relay/how-tos/connect-fluid-azure-service> before pushing the v1.0, any chance this project might be updated so consumers have at least one working example?

**Comment by AndrewCraswell** [comment]
That version is outdated too. It's using these versions of the Fluid Framework packages:

```
"@fluidframework/azure-client": "^0.59.3000",
"@fluidframework/test-client-utils": "^0.59.4001",
"fluid-framework": "^0.59.4001",
```

But all of these have since been updated to v1.0+

**Comment by AndrewCraswell** [comment]
Looks like there's already a PR to bump the packages, it just hasn't been merged yet.
https://github.com/microsoft/FluidExamples/pull/493

Closing this issue.
